elasticsearch:
  build: ./docker/elasticsearch
  volumes:
    - ./docker/elasticsearch:/usr/share/elasticsearch/data
  ports:
    - "9201:9200"
redis:
  container_name: rd02
  image: "redis:latest"
  ports:
    - "6381:6379"